# Generated by Django 4.2 on 2023-04-18 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('university', models.CharField(max_length=100)),
                ('start_date', models.TextField(verbose_name='Date of admission')),
                ('end_date', models.TextField(verbose_name='Graduation date')),
                ('major', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100, verbose_name='City name')),
            ],
            options={
                'db_table': 'education',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Response',
                'verbose_name_plural': 'Responses',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company_name', models.CharField(max_length=100, verbose_name='Company name')),
                ('start_date', models.TextField()),
                ('end_date', models.TextField()),
                ('position', models.CharField()),
                ('responsibilities', models.TextField()),
            ],
            options={
                'db_table': 'work_experience',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('location', models.CharField(max_length=100, verbose_name='Company location')),
                ('position', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('MANAGEMENT', 'MANAGEMENT'), ('PROGRAMMING ', 'PROGRAMMING '), ('SALES', 'SALES'), ('INSURANCE ', 'INSURANCE '), ('FINANCE', 'FINANCE'), ('DESIGN', 'DESIGN')], max_length=100, verbose_name='Job field')),
                ('salary', models.IntegerField(verbose_name='Offered salary')),
                ('description', models.TextField(blank=True, null=True)),
                ('experience_from', models.IntegerField(verbose_name='Expected experience from')),
                ('experience_to', models.IntegerField(verbose_name='Expected experience to')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to=settings.AUTH_USER_MODEL, verbose_name='Vacancy created by')),
            ],
            options={
                'db_table': 'vacancy',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=100, verbose_name='Resume title')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('position', models.CharField()),
                ('category', models.CharField(choices=[('MANAGEMENT', 'MANAGEMENT'), ('PROGRAMMING ', 'PROGRAMMING '), ('SALES', 'SALES'), ('INSURANCE ', 'INSURANCE '), ('FINANCE', 'FINANCE'), ('DESIGN', 'DESIGN')], max_length=100, verbose_name='Job field')),
                ('salary', models.IntegerField(verbose_name='Expected salary')),
                ('telegram', models.URLField(verbose_name='Telegram')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL, verbose_name='Resume created by')),
                ('education', models.ManyToManyField(blank=True, related_name='worker_education', to='job.education')),
                ('work_experience', models.ManyToManyField(blank=True, related_name='worker_experience', to='job.workexperience')),
            ],
            options={
                'db_table': 'resume',
            },
        ),
        migrations.CreateModel(
            name='ResponseMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=3000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_message', to='job.response', verbose_name='Response to vacancy')),
            ],
        ),
        migrations.AddField(
            model_name='response',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_resume', to='job.resume', verbose_name='Resume'),
        ),
        migrations.AddField(
            model_name='response',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_vacancy', to='job.vacancy', verbose_name='Vacancy'),
        ),
    ]
