# Generated by Django 4.2 on 2023-04-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('CANDIDATE', 'Соискатель'), ('EMPLOYER', 'Работодатель')], default='CANDIDATE', max_length=10, verbose_name='Role'),
        ),
    ]
