# Generated by Django 4.2 on 2023-04-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_phone_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('CANDIDATE', 'CANDIDATE'), ('EMPLOYER', 'EMPLOYER')], default='CANDIDATE', max_length=10, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(unique=True, verbose_name='Username'),
        ),
    ]
